### ISSUE TITLE
Failed to read config file: /home/satsale/SatSale/gunicorn.conf.py

### ISSUE THREAD

**Issue by AngeloMetal** [SatSale/SatSale#147]
I have executed the following:
```
git clone https://github.com/nickfarrow/SatSale
cd SatSale/
pip3 install -r requirements.txt
```
I don't use username and password in my Bitcoin Core, so I commented those from ``config.toml`` and uncommented and wrote my cookie file. I guess that would be enough.

But I get this error when attempting to run satsale:
```
satsale@raspibolt:~/SatSale $ gunicorn -w 1 -b 0.0.0.0:8000 satsale:app
Failed to read config file: /home/satsale/SatSale/gunicorn.conf.py
Traceback (most recent call last):
  File "/home/satsale/.local/lib/python3.9/site-packages/toml/decoder.py", line 511, in loads
    ret = decoder.load_line(line, currentlevel, multikey,
  File "/home/satsale/.local/lib/python3.9/site-packages/toml/decoder.py", line 778, in load_line
    value, vtype = self.load_value(pair[1], strictly_valid)
  File "/home/satsale/.local/lib/python3.9/site-packages/toml/decoder.py", line 910, in load_value
    raise ValueError("This float doesn't have a leading "
ValueError: This float doesn't have a leading digit

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/satsale/.local/lib/python3.9/site-packages/gunicorn/app/base.py", line 111, in get_config_from_filename
    spec.loader.exec_module(mod)
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/satsale/SatSale/gunicorn.conf.py", line 1, in <module>
    from gateways import ssh_tunnel
  File "/home/satsale/SatSale/gateways/ssh_tunnel.py", line 5, in <module>
    import config
  File "/home/satsale/SatSale/config.py", line 17, in <module>
    config = toml.load(config_file)
  File "/home/satsale/.local/lib/python3.9/site-packages/toml/decoder.py", line 156, in load
    return loads(f.read(), _dict, decoder)
  File "/home/satsale/.local/lib/python3.9/site-packages/toml/decoder.py", line 514, in loads
    raise TomlDecodeError(str(err), original, pos)
toml.decoder.TomlDecodeError: This float doesn't have a leading digit (line 16 column 1 char 859)

```

**Comment by nickfarrow** [comment]
I think this is the same error as https://github.com/SatSale/SatSale/issues/146

I need to fix these misleading config examples

**Comment by nickfarrow** [comment]
Other possibility is that you missed quotations around a string config line `"`

**Comment by nickfarrow** [comment]
Please reopen if these suggestions (invalid `None`s or missing quotations) do not fix your issue.
