### ISSUE TITLE
SatSale doesn't work with Python 3.10

### ISSUE THREAD

**Issue by kristapsk** [SatSale/SatSale#91]
When starting with Python 3.10, there is error (which seems to be issue with gunicorn / flask_restplus, not SatSale itself):
```
$ python3.10 ~/.local/bin/gunicorn -w 1 -b 0.0.0.0:8000 satsale:app
[2022-08-29 18:07:29 +0300] [24238] [INFO] Starting gunicorn 20.0.4
[2022-08-29 18:07:29 +0300] [24238] [INFO] Listening at: http://0.0.0.0:8000 (24238)
[2022-08-29 18:07:29 +0300] [24238] [INFO] Using worker: sync
[2022-08-29 18:07:29 +0300] [24239] [INFO] Booting worker with pid: 24239
[2022-08-29 18:07:29 +0300] [24239] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.10/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/home/user/.local/lib/python3.10/site-packages/gunicorn/workers/base.py", line 119, in init_process
    self.load_wsgi()
  File "/home/user/.local/lib/python3.10/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/user/.local/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/user/.local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
    return self.load_wsgiapp()
  File "/home/user/.local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/user/.local/lib/python3.10/site-packages/gunicorn/util.py", line 358, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/user/git/SatSale/satsale.py", line 7, in <module>
    from flask_restplus import Resource, Api, fields
  File "/home/user/.local/lib/python3.10/site-packages/flask_restplus/__init__.py", line 4, in <module>
    from . import fields, reqparse, apidoc, inputs, cors
  File "/home/user/.local/lib/python3.10/site-packages/flask_restplus/reqparse.py", line 19, in <module>
    from .model import Model
  File "/home/user/.local/lib/python3.10/site-packages/flask_restplus/model.py", line 8, in <module>
    from collections import OrderedDict, MutableMapping
ImportError: cannot import name 'MutableMapping' from 'collections' (/usr/lib/python3.10/collections/__init__.py)
[2022-08-29 18:07:29 +0300] [24239] [INFO] Worker exiting (pid: 24239)
[2022-08-29 18:07:29 +0300] [24238] [INFO] Shutting down: Master
[2022-08-29 18:07:29 +0300] [24238] [INFO] Reason: Worker failed to boot.
```

Seems to be this issue - https://stackoverflow.com/questions/70870041/cannot-import-name-mutablemapping-from-collections.

**Comment by kristapsk** [comment]
After #99 solving above error, now have next one:
```
$ python3.10 ~/.local/bin/gunicorn -w 1 -b 0.0.0.0:8000 satsale:app
[2022-09-17 12:25:42 +0300] [28957] [INFO] Starting gunicorn 20.0.4
[2022-09-17 12:25:42 +0300] [28957] [INFO] Listening at: http://0.0.0.0:8000 (28957)
[2022-09-17 12:25:42 +0300] [28957] [INFO] Using worker: sync
[2022-09-17 12:25:42 +0300] [28959] [INFO] Booting worker with pid: 28959
[2022-09-17 12:25:43 +0300] [28959] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.10/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/home/user/.local/lib/python3.10/site-packages/gunicorn/workers/base.py", line 119, in init_process
    self.load_wsgi()
  File "/home/user/.local/lib/python3.10/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/user/.local/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/user/.local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
    return self.load_wsgiapp()
  File "/home/user/.local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/user/.local/lib/python3.10/site-packages/gunicorn/util.py", line 358, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/user/git/SatSale/satsale.py", line 28, in <module>
    from node import xpub
  File "/home/user/git/SatSale/node/xpub.py", line 5, in <module>
    from bip_utils import Bip84, Bip44Changes, Bip84Coins, Bip44, Bip44Coins
  File "/home/user/.local/lib/python3.10/site-packages/bip_utils/__init__.py", line 5, in <module>
    from bip_utils.addr import (
  File "/home/user/.local/lib/python3.10/site-packages/bip_utils/addr/__init__.py", line 1, in <module>
    from bip_utils.addr.ada_byron_addr import (
  File "/home/user/.local/lib/python3.10/site-packages/bip_utils/addr/ada_byron_addr.py", line 41, in <module>
    from bip_utils.base58 import Base58Decoder, Base58Encoder
  File "/home/user/.local/lib/python3.10/site-packages/bip_utils/base58/__init__.py", line 1, in <module>
    from bip_utils.base58.base58 import Base58Alphabets, Base58Decoder, Base58Encoder
  File "/home/user/.local/lib/python3.10/site-packages/bip_utils/base58/base58.py", line 28, in <module>
    from bip_utils.utils.crypto import DoubleSha256
  File "/home/user/.local/lib/python3.10/site-packages/bip_utils/utils/crypto/__init__.py", line 1, in <module>
    from bip_utils.utils.crypto.aes_ecb import AesEcbDecrypter, AesEcbEncrypter
  File "/home/user/.local/lib/python3.10/site-packages/bip_utils/utils/crypto/aes_ecb.py", line 29, in <module>
    from Crypto.Cipher import AES
  File "/home/user/.local/lib/python3.10/site-packages/Crypto/Cipher/__init__.py", line 31, in <module>
    from Crypto.Cipher._mode_ctr import _create_ctr_cipher
  File "/home/user/.local/lib/python3.10/site-packages/Crypto/Cipher/_mode_ctr.py", line 37, in <module>
    from Crypto.Util.number import long_to_bytes
  File "/home/user/.local/lib/python3.10/site-packages/Crypto/Util/number.py", line 399
    s = pack('>I', n & 0xffffffffL) + s
                                ^
SyntaxError: invalid hexadecimal literal
[2022-09-17 12:25:43 +0300] [28959] [INFO] Worker exiting (pid: 28959)
[2022-09-17 12:25:43 +0300] [28957] [INFO] Shutting down: Master
[2022-09-17 12:25:43 +0300] [28957] [INFO] Reason: Worker failed to boot.
```

**Comment by kristapsk** [comment]
Found the problem - even current master of bip_utils requires pycryptodome 3.6, which has 0xffffffffL instead of 0xFFFFFFFF in code, incompatible with latest Python versions. So, we need fix in bip_utils, not here (bip_utils itself is compatible with Python 3.10, problem is dependency on old version of pycryptodome).

**Comment by kristapsk** [comment]
Hmm, or it is just problem on my machine. Did `pip uninstall pycryptodome` and then `pip install -r requirements.txt --user` again and now it has recent enough pycyptodome and no more error.

**Comment by kristapsk** [comment]
Did upgrade to Python 3.10 on a different machine, everything seems to working after merge of #99, so closing.
